# type: ignore
"""intitialize

Revision ID: b1a559c9fdf3
Revises: 
Create Date: 2024-10-22 23:47:47.936369+00:00

"""
# pylint: skip-file

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from users_api.enums import *
from users_api.db.type_utils import *





# revision identifiers, used by Alembic.
revision = 'b1a559c9fdf3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', TZDateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('last_updated', TZDateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('sms', sa.String(), nullable=True),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', TZDateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('last_updated', TZDateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_and_posts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_and_posts')
    op.drop_table('users')
    op.drop_table('posts')
    # ### end Alembic commands ###
