# type: ignore
"""intialize

Revision ID: b88eb3fd142a
Revises: 
Create Date: 2024-10-15 05:23:47.758711+00:00

"""
# pylint: skip-file

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from users_api.enums import *
from users_api.db.type_utils import *





# revision identifiers, used by Alembic.
revision = 'b88eb3fd142a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('sms', sa.String(), nullable=True),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', TZDateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('last_updated', TZDateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
